#!/usr/bin/env python3
"""Build a PS3 PPU PRX with the open-source powerpc64 toolchain.

  mkprx.py imports <config.json> <out.S>
      Writes a call stub and an import slot for every function in the config's "imports".
      A function is a name, or {"nid": "0x...", "symbol": "..."} for libraries whose names
      aren't public (vshtask, paf, vshmain).
  mkprx.py pack <config.json> <in.elf> <out.prx>
      Turns an ELF linked with prx/prx.ld and --emit-relocs into a PRX: two segments, the
      module info, export/import tables, LV2 function descriptors and PRX relocations.

gcc's ELFv1 code reaches data TOC-relative, so code needs no load-time fixups. Every
absolute address (data pointers, gcc's 24-byte descriptors) becomes a 32-bit PRX
relocation, because the PS3 loads each segment at its own address.
"""
import hashlib
import json
import struct
import sys

NID_SUFFIX = bytes.fromhex("6759659904250490566427499489741A")
NID_MODULE_START, NID_MODULE_STOP, NID_MODULE_INFO = 0xBC9A0086, 0xAB779874, 0xD7F43016

R_PPC64_NONE, R_PPC64_ADDR32, R_PPC64_ADDR16_LO, R_PPC64_ADDR16_HI, R_PPC64_ADDR16_HA = 0, 1, 4, 5, 6
R_PPC64_REL24, R_PPC64_REL14, R_PPC64_REL32, R_PPC64_ADDR64, R_PPC64_REL64, R_PPC64_TOC = 10, 11, 26, 38, 44, 51
TOC_RELATIVE = {47, 48, 49, 50, 63, 64}  # TOC16, _LO, _HI, _HA, _DS, _LO_DS
PC_RELATIVE = {R_PPC64_REL24, R_PPC64_REL14, R_PPC64_REL32, R_PPC64_REL64}

DATA_BASE = 0x10000000  # must match prx/prx.ld


def nid(name):
    return struct.unpack("<I", hashlib.sha1(name.encode() + NID_SUFFIX).digest()[:4])[0]


def func_entries(funcs):
    """Config functions → [(nid, symbol)], sorted by NID like Sony's tables."""
    out = []
    for f in funcs:
        if isinstance(f, str):
            out.append((nid(f), f))
        else:
            out.append((int(f["nid"], 16) if "nid" in f else nid(f["name"]), f["symbol"]))
    return sorted(out)


# ---------------------------------------------------------------- import stubs

STUB = """
	.section ".opd","aw"
	.align 3
	.globl {sym}
{sym}:
	.quad .L.{sym},.TOC.@tocbase,0
	.previous
	.type {sym}, @function
.L.{sym}:
	mflr 0
	std 0,16(1)
	stdu 1,-128(1)
	std 2,40(1)
	addis 12,2,{slot}@toc@ha
	lwz 12,{slot}@toc@l(12)
	lwz 0,0(12)
	lwz 2,4(12)
	mtctr 0
	bctrl
	ld 2,40(1)
	addi 1,1,128
	ld 0,16(1)
	mtlr 0
	blr
	.size {sym},.-.L.{sym}
"""


def cmd_imports(cfg, out_path):
    lines = ["# Generated by mkprx.py. Do not edit.",
             "# Each stub saves our TOC, calls through the LV2 descriptor the loader put in the slot,",
             "# then restores the TOC (the caller's 'nop' after 'bl' won't do it).",
             '\t.section ".text"', "\t.align 2"]
    for lib in cfg.get("imports", []):
        for n, sym in func_entries(lib["functions"]):
            lines.append(STUB.format(sym=sym, slot=f"__prx_slot_{sym}"))
    lines += ['\t.section ".data.prx_slots","aw"', "\t.align 2"]
    for lib in cfg.get("imports", []):
        lines.append(f"\t.globl __prx_slots_{lib['library']}")
        lines.append(f"__prx_slots_{lib['library']}:")
        for n, sym in func_entries(lib["functions"]):
            lines.append(f"__prx_slot_{sym}:\t.long 0\t# NID 0x{n:08x}")
    # __prx_imports: {name, slot} pairs ending in {0, 0}, so the module can check its slots
    # were linked before calling through them (src/common/prx.c).
    lines += ['\t.section ".rodata"']
    for lib in cfg.get("imports", []):
        for n, sym in func_entries(lib["functions"]):
            lines.append(f'.L.name.{sym}:\t.string "{lib["library"]}.{sym}"')
    lines += ['\t.section ".data.rel.ro","aw"', "\t.align 3", "\t.globl __prx_imports", "__prx_imports:"]
    for lib in cfg.get("imports", []):
        for n, sym in func_entries(lib["functions"]):
            lines.append(f"\t.quad .L.name.{sym}, __prx_slot_{sym}")
    lines.append("\t.quad 0, 0")
    open(out_path, "w").write("\n".join(lines) + "\n")


# ---------------------------------------------------------------- ELF reading

class LinkedElf:
    def __init__(self, data):
        self.d = data
        assert data[:4] == b"\x7fELF" and data[4] == 2 and data[5] == 2, "need a 64-bit big-endian ELF"
        shoff, = struct.unpack_from(">Q", data, 0x28)
        shentsize, shnum, shstrndx = struct.unpack_from(">HHH", data, 0x3A)
        self.sections = []
        for i in range(shnum):
            (name, typ, flags, addr, off, size, link, info, align, entsize) = struct.unpack_from(
                ">IIQQQQIIQQ", data, shoff + i * shentsize)
            self.sections.append(dict(name=name, type=typ, flags=flags, addr=addr, off=off, size=size,
                                      link=link, info=info, entsize=entsize))
        strtab = self.sections[shstrndx]
        for s in self.sections:
            s["name"] = self._str(strtab, s["name"])
        symtab = next(s for s in self.sections if s["type"] == 2)
        self.symbols = []
        for i in range(symtab["size"] // 24):
            (name, info, other, shndx, value, size) = struct.unpack_from(">IBBHQQ", data, symtab["off"] + i * 24)
            self.symbols.append(dict(name=self._str(self.sections[symtab["link"]], name),
                                     info=info, shndx=shndx, value=value))
        self.by_name = {s["name"]: s for s in self.symbols if s["name"] and s["shndx"] != 0}

    def _str(self, sec, off):
        o = sec["off"] + off
        return self.d[o:self.d.index(b"\0", o)].decode()

    def relocations(self):
        """(place, type, target) for every relocation on a loaded section."""
        for s in self.sections:
            if s["type"] != 4 or not (self.sections[s["info"]]["flags"] & 2):
                continue
            for i in range(s["size"] // 24):
                off, info, addend = struct.unpack_from(">QQq", self.d, s["off"] + i * 24)
                sym, typ = info >> 32, info & 0xFFFFFFFF
                if sym == 0:
                    target = addend
                else:
                    symbol = self.symbols[sym]
                    if symbol["shndx"] == 0:
                        raise SystemExit(f"undefined symbol '{symbol['name']}' (missing import or function?)")
                    target = symbol["value"] + addend
                yield off, typ, target, (self.symbols[sym]["name"] if sym else "")


# ---------------------------------------------------------------- PRX building

class Segment:
    def __init__(self, base, image, memsz):
        self.base, self.image, self.memsz = base, bytearray(image), memsz

    def append(self, blob, align=4):
        # Anything appended goes after .bss, so the zero-filled .bss becomes file data.
        self.image += bytes(self.memsz - len(self.image))
        self.image += bytes(-len(self.image) % align)
        at = len(self.image)
        self.image += blob
        self.memsz = len(self.image)
        return at  # offset inside the segment


class PrxBuilder:
    def __init__(self, elf):
        self.elf = elf
        text, data = [], []
        for s in elf.sections:
            if s["flags"] & 2 and s["size"]:
                (data if s["addr"] >= DATA_BASE else text).append(s)
        self.segs = [self._image(text, 0), self._image(data, DATA_BASE)]
        self.relocs = []  # (patched seg, offset, type, target seg, target offset)

    def _image(self, sections, base):
        end = max((s["addr"] + s["size"] for s in sections), default=base)
        image = bytearray(max((s["addr"] + s["size"] for s in sections if s["type"] != 8), default=base) - base)
        for s in sections:
            if s["type"] != 8:  # NOBITS
                image[s["addr"] - base:s["addr"] - base + s["size"]] = self.elf.d[s["off"]:s["off"] + s["size"]]
        return Segment(base, image, end - base)

    def seg_of(self, addr):
        return 1 if addr >= DATA_BASE else 0

    def ref(self, seg, off, target_seg, target_off, typ=R_PPC64_ADDR32):
        self.relocs.append((seg, off, typ, target_seg, target_off))

    def convert_elf_relocations(self):
        self.toc = None
        for place, typ, target, symname in self.elf.relocations():
            pseg, tseg = self.seg_of(place), self.seg_of(target)
            poff, toff = place - self.segs[pseg].base, target - self.segs[tseg].base
            if typ == R_PPC64_NONE:
                continue
            if typ in TOC_RELATIVE:
                # The TOC is in the data segment, so the target must be too.
                if tseg != 1:
                    raise SystemExit(f"TOC-relative reference to code at 0x{place:x} ({symname})")
                continue
            if typ in (R_PPC64_REL24, R_PPC64_REL14):
                # ELFv1 branches name the function descriptor, but ld branches to the code,
                # so check the target encoded in the instruction instead.
                insn, = struct.unpack_from(">I", self.segs[pseg].image, poff)
                disp = (insn & 0x03FFFFFC) if typ == R_PPC64_REL24 else (insn & 0xFFFC)
                bits = 26 if typ == R_PPC64_REL24 else 16
                disp -= (disp & (1 << (bits - 1))) << 1
                if self.seg_of(place + disp) != pseg:
                    raise SystemExit(f"branch across segments at 0x{place:x} ({symname})")
                continue
            if typ in PC_RELATIVE:
                if pseg != tseg:
                    raise SystemExit(f"PC-relative reference across segments at 0x{place:x} ({symname})")
                continue
            if typ == R_PPC64_TOC:
                # ld doesn't always emit a .TOC. symbol, but it has written the value here.
                target, = struct.unpack_from(">Q", self.segs[pseg].image, poff)
                if self.toc not in (None, target):
                    raise SystemExit("more than one TOC (the module must use a single TOC)")
                self.toc, typ = target, R_PPC64_ADDR64
                tseg, toff = 1, target - DATA_BASE
            if typ == R_PPC64_ADDR64:
                # Addresses are 32-bit on the PS3: zero the high word, relocate the low word.
                struct.pack_into(">II", self.segs[pseg].image, poff, 0, target & 0xFFFFFFFF)
                self.ref(pseg, poff + 4, tseg, toff)
            elif typ in (R_PPC64_ADDR32, R_PPC64_ADDR16_LO, R_PPC64_ADDR16_HI, R_PPC64_ADDR16_HA):
                self.ref(pseg, poff, tseg, toff, typ)
            else:
                raise SystemExit(f"unsupported relocation type {typ} at 0x{place:x} ({symname})")

    def lv2_opd(self, symbol):
        """An 8-byte LV2 descriptor (code address, TOC) in the data segment for a gcc function."""
        sym = self.elf.by_name.get(symbol)
        if sym is None:
            raise SystemExit(f"exported function '{symbol}' isn't defined")
        opd = sym["value"] - DATA_BASE
        entry, toc = struct.unpack_from(">QQ", self.segs[1].image, opd)
        at = self.segs[1].append(struct.pack(">II", entry, toc), 8)
        self.ref(1, at, 0, entry)
        self.ref(1, at + 4, 1, toc - DATA_BASE)
        return at

    def build(self, cfg):
        self.convert_elf_relocations()
        text = self.segs[0]

        def cstr(s):
            return text.append(s.encode() + b"\0", 4)

        def u32_array(values, targets=None):
            at = text.append(b"".join(struct.pack(">I", v) for v in values), 4)
            for i, t in enumerate(targets or []):
                self.ref(0, at + 4 * i, *t)
            return at

        # Module management exports: module_start, module_stop, then variables.
        mgmt_funcs = [(NID_MODULE_START, cfg["start"]), (NID_MODULE_STOP, cfg["stop"])]
        mgmt_vars = [(int(k, 16), v) for k, v in cfg.get("management_vars", {}).items()]
        mgmt_targets = [(1, self.lv2_opd(sym)) for _, sym in mgmt_funcs]
        modinfo_placeholder = len(mgmt_targets)  # filled once the module info's offset is known
        mgmt_targets.append(None)
        for _, value in mgmt_vars:
            mgmt_targets.append((1, self.segs[1].append(struct.pack(">I", value), 4)))
        mgmt_nids = [n for n, _ in mgmt_funcs] + [NID_MODULE_INFO] + [n for n, _ in mgmt_vars]

        libents = []  # (attr, version, nfunc, nvar, info_hash, name_off or None, nids_off, addrs_off)
        mgmt_nids_off = u32_array(mgmt_nids)
        mgmt_addrs_off = text.append(bytes(4 * len(mgmt_nids)), 4)
        libents.append((0x8000, 0, 2, len(mgmt_nids) - 2, 0, None, mgmt_nids_off, mgmt_addrs_off))

        for lib in cfg.get("exports", []):
            funcs = func_entries(lib["functions"])
            name_off = cstr(lib["library"])
            nids_off = u32_array([n for n, _ in funcs])
            addrs_off = u32_array([0] * len(funcs), [(1, self.lv2_opd(sym)) for _, sym in funcs])
            libents.append((lib.get("attributes", 9), lib.get("version", 1), len(funcs), 0,
                            lib.get("info_hash", 0), name_off, nids_off, addrs_off))

        stubs = []
        for lib in cfg.get("imports", []):
            funcs = func_entries(lib["functions"])
            name_off = cstr(lib["library"])
            nids_off = u32_array([n for n, _ in funcs])
            slots = self.elf.by_name[f"__prx_slots_{lib['library']}"]["value"] - DATA_BASE
            stubs.append((lib.get("attributes", 9), lib.get("version", 1), len(funcs), name_off, nids_off, slots))

        # Export table (0x1c-byte entries).
        exports_start = text.append(b"", 8)
        for (attr, ver, nfunc, nvar, info_hash, name_off, nids_off, addrs_off) in libents:
            at = text.append(struct.pack(">BBHHHHHBBHIII", 0x1C, 0, ver, attr, nfunc, nvar, 0, info_hash, 0, 0,
                                         0, 0, 0), 4)
            if name_off is not None:
                self.ref(0, at + 0x10, 0, name_off)
            self.ref(0, at + 0x14, 0, nids_off)
            self.ref(0, at + 0x18, 0, addrs_off)
        exports_end = len(text.image)

        # Import table (0x2c-byte entries).
        imports_start = text.append(b"", 8)
        for (attr, ver, nfunc, name_off, nids_off, slots) in stubs:
            at = text.append(struct.pack(">BBHHHHHBBHIIIIIII", 0x2C, 0, ver, attr, nfunc, 0, 0, 0, 0, 0,
                                         0, 0, 0, 0, 0, 0, 0), 4)
            self.ref(0, at + 0x10, 0, name_off)
            self.ref(0, at + 0x14, 0, nids_off)
            self.ref(0, at + 0x18, 1, slots)
        imports_end = len(text.image)

        # Module info: pointed to by the first segment's p_paddr.
        toc = self.toc - DATA_BASE
        name = cfg["module_name"].encode()
        assert len(name) < 28
        modinfo = text.append(struct.pack(">HBB28sIIIII", cfg.get("attributes", 0), *cfg.get("version", [1, 1]),
                                          name, 0, 0, 0, 0, 0), 4)
        self.ref(0, modinfo + 0x20, 1, toc)
        self.ref(0, modinfo + 0x24, 0, exports_start)
        self.ref(0, modinfo + 0x28, 0, exports_end)
        self.ref(0, modinfo + 0x2C, 0, imports_start)
        self.ref(0, modinfo + 0x30, 0, imports_end)

        mgmt_targets[modinfo_placeholder] = (0, modinfo)
        for i, t in enumerate(mgmt_targets):
            self.ref(0, mgmt_addrs_off + 4 * i, *t)
        return modinfo

    def write(self, path, modinfo):
        seg0, seg1 = self.segs
        # Pad the code so the data segment follows it directly, as in Sony's PRXs.
        seg0.image += bytes(((seg0.memsz + 0xFF) & ~0xFF) - len(seg0.image))
        seg1_vaddr = len(seg0.image)
        # Store each pointer as it would be with the segments at their p_vaddr (like Sony's
        # files), so the unloaded file reads sensibly. The loader overwrites these anyway.
        for (pseg, poff, typ, tseg, toff) in self.relocs:
            if typ == R_PPC64_ADDR32:
                struct.pack_into(">I", self.segs[pseg].image, poff, toff + (seg1_vaddr if tseg else 0))
        rel = b"".join(struct.pack(">QHBBIQ", poff, 0, tseg, pseg, typ, toff)
                       for (pseg, poff, typ, tseg, toff) in self.relocs)

        phoff, phnum = 0x40, 3
        off0 = (phoff + phnum * 0x38 + 0xF) & ~0xF
        off1 = (off0 + len(seg0.image) + 0xF) & ~0xF
        offr = (off1 + len(seg1.image) + 0xF) & ~0xF
        out = bytearray(offr + len(rel))
        out[0:16] = b"\x7fELF\x02\x02\x01\x66" + bytes(8)  # ELFOSABI 0x66: CELL LV2
        struct.pack_into(">HHIQQQIHHHHHH", out, 16, 0xFFA4, 21, 1, 0, phoff, 0, 0x01000000, 0x40, 0x38, phnum,
                         0, 0, 0)
        phdrs = [
            (1, 0x400005, off0, 0, off0 + modinfo, len(seg0.image), len(seg0.image), 0x10),
            (1, 0x600006, off1, seg1_vaddr, 0, len(seg1.image), seg1.memsz, 0x10),
            (0x700000A4, 0, offr, 0, 0, len(rel), 0, 0x10),
        ]
        for i, p in enumerate(phdrs):
            struct.pack_into(">IIQQQQQQ", out, phoff + i * 0x38, *p)
        out[off0:off0 + len(seg0.image)] = seg0.image
        out[off1:off1 + len(seg1.image)] = seg1.image
        out[offr:] = rel
        open(path, "wb").write(out)
        print(f"{path}: text 0x{len(seg0.image):x}, data 0x{len(seg1.image):x}/0x{seg1.memsz:x}, "
              f"{len(self.relocs)} relocations")


def main():
    if len(sys.argv) < 4:
        raise SystemExit(__doc__)
    cfg = json.load(open(sys.argv[2]))
    if sys.argv[1] == "imports":
        cmd_imports(cfg, sys.argv[3])
    elif sys.argv[1] == "pack":
        builder = PrxBuilder(LinkedElf(open(sys.argv[3], "rb").read()))
        modinfo = builder.build(cfg)
        builder.write(sys.argv[4], modinfo)
    else:
        raise SystemExit(__doc__)


if __name__ == "__main__":
    main()
