/* PS3 (LV2) types, system calls and the sysPrxForUser imports both modules use. */
#pragma once

#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>

typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef int32_t s32;
typedef int64_t s64;

#define CELL_OK 0

/* Pointers inside PS3 structs are 32-bit, but ours are 64-bit, so they're stored as u32. */
#define PTR(addr) ((void *)(uintptr_t)(u32)(addr))

/* System call: number in r11, arguments in r3-r10, result in r3 (clobbers as in PSL1GHT). */
static inline u64 lv2_syscall(u64 num, u64 a1, u64 a2, u64 a3, u64 a4, u64 a5, u64 a6)
{
	register u64 r3 __asm__("r3") = a1;
	register u64 r4 __asm__("r4") = a2;
	register u64 r5 __asm__("r5") = a3;
	register u64 r6 __asm__("r6") = a4;
	register u64 r7 __asm__("r7") = a5;
	register u64 r8 __asm__("r8") = a6;
	register u64 r11 __asm__("r11") = num;
	__asm__ volatile("sc"
			 : "+r"(r3), "+r"(r4), "+r"(r5), "+r"(r6), "+r"(r7), "+r"(r8), "+r"(r11)
			 :
			 : "r0", "r9", "r10", "r12", "lr", "ctr", "xer", "cr0", "cr1", "cr5", "cr6", "cr7",
			   "memory");
	return r3;
}

/* File system (cellFs is a thin wrapper over these). */
#define CELL_FS_O_RDONLY 0x000000
#define CELL_FS_O_WRONLY 0x000001
#define CELL_FS_O_CREAT  0x000040
#define CELL_FS_O_TRUNC  0x000200
#define CELL_FS_O_APPEND 0x000400
#define CELL_FS_ERROR_ENOENT 0x80010006

static inline s32 sys_fs_open(const char *path, s32 flags, s32 *fd, u64 mode)
{
	return (s32)lv2_syscall(801, (uintptr_t)path, flags, (uintptr_t)fd, mode, 0, 0);
}
static inline s32 sys_fs_read(s32 fd, void *buf, u64 size, u64 *read)
{
	return (s32)lv2_syscall(802, fd, (uintptr_t)buf, size, (uintptr_t)read, 0, 0);
}
static inline s32 sys_fs_write(s32 fd, const void *buf, u64 size, u64 *written)
{
	return (s32)lv2_syscall(803, fd, (uintptr_t)buf, size, (uintptr_t)written, 0, 0);
}
static inline s32 sys_fs_close(s32 fd)
{
	return (s32)lv2_syscall(804, fd, 0, 0, 0, 0, 0);
}
static inline s32 sys_fs_mkdir(const char *path, u32 mode)
{
	return (s32)lv2_syscall(811, (uintptr_t)path, mode, 0, 0, 0, 0);
}
static inline s32 sys_fs_rename(const char *from, const char *to)
{
	return (s32)lv2_syscall(812, (uintptr_t)from, (uintptr_t)to, 0, 0, 0, 0);
}
static inline s32 sys_fs_unlink(const char *path)
{
	return (s32)lv2_syscall(814, (uintptr_t)path, 0, 0, 0, 0, 0);
}

/* Process. The PARAM.SFO buffer is 0x40 bytes, with the title ID at +1. */
static inline u32 sys_process_getpid(void)
{
	return (u32)lv2_syscall(1, 0, 0, 0, 0, 0, 0);
}
static inline s32 sys_process_get_paramsfo(u8 *buffer)
{
	return (s32)lv2_syscall(30, (uintptr_t)buffer, 0, 0, 0, 0, 0);
}

/* Fails for an unmapped address, so we can check a pointer before reading through it. */
typedef struct {
	u64 attribute;
	u64 access_right;
	u32 page_size;
	u32 pad;
} sys_page_attr_t;

static inline s32 sys_memory_get_page_attribute(u32 addr, sys_page_attr_t *attr)
{
	return (s32)lv2_syscall(351, addr, (uintptr_t)attr, 0, 0, 0, 0);
}

/* PRX management and the raw thread exit, used to end Cobra's start/stop threads (prx.c). */
static inline s32 sys_prx_get_module_id_by_address(u32 addr)
{
	return (s32)lv2_syscall(461, addr, 0, 0, 0, 0, 0);
}
static inline s32 sys_prx_stop_module(s32 id, u64 flags, void *opt)
{
	return (s32)lv2_syscall(482, (u64)(s64)id, flags, (uintptr_t)opt, 0, 0, 0);
}
__attribute__((noreturn)) static inline void sys_ppu_thread_exit_raw(u64 value)
{
	lv2_syscall(41, value, 0, 0, 0, 0, 0);
	__builtin_unreachable();
}

static inline u64 sys_time_get_timebase_frequency(void)
{
	return lv2_syscall(147, 0, 0, 0, 0, 0, 0);
}

static inline void sys_timer_usleep(u64 usec)
{
	lv2_syscall(141, usec, 0, 0, 0, 0, 0);
}
static inline void sys_ppu_thread_yield(void)
{
	lv2_syscall(43, 0, 0, 0, 0, 0, 0);
}
static inline s32 sys_ppu_thread_join(u64 thread_id, u64 *value)
{
	return (s32)lv2_syscall(44, thread_id, (uintptr_t)value, 0, 0, 0, 0);
}

/* sysPrxForUser (liblv2): stubs generated by mkprx.py from prx/<module>.json.
   Most liblv2 functions read the calling thread's TLS (r13). Cobra runs module_start and
   module_stop on threads the kernel creates, which have none, so only these two are used:
   thread_create works there (webMAN relies on it), and thread_exit only runs on our threads. */
#define SYS_PPU_THREAD_CREATE_JOINABLE 1

s32 sys_ppu_thread_create(u64 *thread_id, const void *entry_opd, u64 arg, s32 prio, u64 stack_size, u64 flags,
			  const char *name);
void sys_ppu_thread_exit(u64 value) __attribute__((noreturn));

/* libc.c */
void *memset(void *dst, int c, size_t n);
void *memcpy(void *dst, const void *src, size_t n);
size_t strlen(const char *s);
int strcmp(const char *a, const char *b);
int strcasecmp(const char *a, const char *b);
