#include "prx.h"
#include "log.h"

/* Section bounds from prx/prx.ld. Code can't reach the code segment TOC-relative, so the
   addresses are kept in data, where the loader relocates them. */
extern const char __prx_text_start[], __prx_text_end[], __prx_data_start[], __prx_data_end[];
static const char *volatile bounds[4] = { __prx_text_start, __prx_text_end, __prx_data_start, __prx_data_end };

/* Generated by mkprx.py: one {name, slot} per import, ending in {NULL, NULL}. */
typedef struct {
	const char *name;
	const u32 *slot;
} prx_import_t;
extern const prx_import_t __prx_imports[];

/* sceLibStub: one imported library in an executable or PRX. */
typedef struct {
	u8 size, unk0;
	u16 version, attributes, num_func, num_var, num_tlsvar;
	u8 info_hash, info_tlshash;
	u16 unk1;
	u32 name, nids, slots, vnids, vstubs, unk4, unk5;
} lib_stub_t;

void prx_make_opd(lv2_opd_t *opd, void (*fn)(void))
{
	const u64 *gcc_opd = (const u64 *)(uintptr_t)fn; /* gcc's 24-byte descriptor: entry, TOC, env */
	opd->entry = (u32)gcc_opd[0];
	opd->toc = (u32)gcc_opd[1];
}

void prx_log_layout(void)
{
	u64 toc;
	__asm__("mr %0,2" : "=r"(toc));
	log_printf("module: code 0x%08lx-0x%08lx, data 0x%08lx-0x%08lx, toc 0x%08lx", (uintptr_t)bounds[0],
		   (uintptr_t)bounds[1], (uintptr_t)bounds[2], (uintptr_t)bounds[3], toc);
}

/* The game's import table for `lib`, through its ELF header (mapped at 0x10000) and the PRX
   parameter segment. */
static const lib_stub_t *find_game_import(const char *lib)
{
	const u8 *elf = PTR(0x10000);
	if (elf[0] != 0x7F || elf[1] != 'E' || elf[2] != 'L' || elf[3] != 'F')
		return NULL;
	u64 phoff = *(const u64 *)(elf + 0x20);
	u16 phnum = *(const u16 *)(elf + 0x38);
	for (u16 i = 0; i < phnum; i++) {
		const u8 *ph = elf + phoff + i * 0x38;
		if (*(const u32 *)ph != 0x60000002)
			continue;
		const u32 *param = PTR(*(const u64 *)(ph + 0x10));
		if (param[1] != 0x1B434CEC)
			return NULL;
		for (u32 at = param[6]; at < param[7];) {
			const lib_stub_t *stub = PTR(at);
			if (stub->name && strcmp(PTR(stub->name), lib) == 0)
				return stub;
			at += stub->size ? stub->size : sizeof(lib_stub_t);
		}
	}
	return NULL;
}

u32 *prx_find_game_slot(const char *lib, u32 nid)
{
	const lib_stub_t *stub = find_game_import(lib);
	if (!stub)
		return NULL;
	const u32 *nids = PTR(stub->nids);
	for (u32 i = 0; i < stub->num_func; i++)
		if (nids[i] == nid)
			return (u32 *)PTR(stub->slots) + i;
	return NULL;
}

int prx_read_opd(u32 addr, lv2_opd_t *out)
{
	sys_page_attr_t attr;
	if (addr < 0x10000 || (addr & 3) || sys_memory_get_page_attribute(addr, &attr) != CELL_OK)
		return 0;
	*out = *(const lv2_opd_t *)PTR(addr);
	return 1;
}

void prx_end_start(void)
{
	log_printf("module_start done");
	sys_ppu_thread_exit_raw(0); /* 0 = SYS_PRX_RESIDENT: stay loaded */
}

void prx_end_stop(void)
{
	/* What liblv2 sends after calling module_stop itself: size, command 2 (done), entry, result. */
	u64 done[5] = { 0x28, 2, 0, 0, 0 };
	s32 id = sys_prx_get_module_id_by_address((u32)(uintptr_t)bounds[0]);
	s32 result = sys_prx_stop_module(id, 0, done);
	log_printf("module_stop done (module 0x%x, stop reported 0x%x)", id, result);
	sys_ppu_thread_exit_raw(0);
}

int prx_check_imports(void)
{
	int linked = 1;
	for (const prx_import_t *i = __prx_imports; i->name; i++) {
		lv2_opd_t opd;
		sys_page_attr_t attr;
		u32 slot = *i->slot;
		if (prx_read_opd(slot, &opd) && sys_memory_get_page_attribute(opd.entry, &attr) == CELL_OK) {
			log_printf("import %s: 0x%08x -> [0x%08x, toc 0x%08x]", i->name, slot, opd.entry, opd.toc);
		} else {
			log_printf("import %s: NOT LINKED (slot 0x%08x)", i->name, slot);
			linked = 0;
		}
	}
	return linked;
}
